/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountLinksRouteImport } from './routes/account-links'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountLinksIndexRouteImport } from './routes/account-links.index'
import { Route as AccountLinksUserIdRouteImport } from './routes/account-links.$userId'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminOnlineRouteImport } from './routes/admin/online'
import { Route as AzerothStatusRouteImport } from './routes/azeroth/status'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CharactersNameRouteImport } from './routes/characters/$name'
import { Route as IdentityUsersRouteImport } from './routes/identity/users'
import { Route as ItemsIndexRouteImport } from './routes/items/index'
import { Route as ItemsEntryRouteImport } from './routes/items/$entry'
import { Route as StoreProductsRouteImport } from './routes/store/products'
import { Route as StoreWalletRouteImport } from './routes/store/wallet'
import { Route as IdentityUsersIndexRouteImport } from './routes/identity/users.index'
import { Route as StoreProductsIndexRouteImport } from './routes/store/products.index'
import { Route as StoreProductsSkuRouteImport } from './routes/store/products.$sku'
import { Route as IdentityUsersUserIdCharactersRouteImport } from './routes/identity/users.$userId.characters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLinksRoute = AccountLinksRouteImport.update({
  id: '/account-links',
  path: '/account-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLinksIndexRoute = AccountLinksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountLinksRoute,
} as any)
const AccountLinksUserIdRoute = AccountLinksUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AccountLinksRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnlineRoute = AdminOnlineRouteImport.update({
  id: '/admin/online',
  path: '/admin/online',
  getParentRoute: () => rootRouteImport,
} as any)
const AzerothStatusRoute = AzerothStatusRouteImport.update({
  id: '/azeroth/status',
  path: '/azeroth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersNameRoute = CharactersNameRouteImport.update({
  id: '/characters/$name',
  path: '/characters/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityUsersRoute = IdentityUsersRouteImport.update({
  id: '/identity/users',
  path: '/identity/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsEntryRoute = ItemsEntryRouteImport.update({
  id: '/items/$entry',
  path: '/items/$entry',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProductsRoute = StoreProductsRouteImport.update({
  id: '/store/products',
  path: '/store/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreWalletRoute = StoreWalletRouteImport.update({
  id: '/store/wallet',
  path: '/store/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityUsersIndexRoute = IdentityUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdentityUsersRoute,
} as any)
const StoreProductsIndexRoute = StoreProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreProductsRoute,
} as any)
const StoreProductsSkuRoute = StoreProductsSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => StoreProductsRoute,
} as any)
const IdentityUsersUserIdCharactersRoute =
  IdentityUsersUserIdCharactersRouteImport.update({
    id: '/$userId/characters',
    path: '/$userId/characters',
    getParentRoute: () => IdentityUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-links': typeof AccountLinksRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/login': typeof LoginRoute
  '/account-links/$userId': typeof AccountLinksUserIdRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/online': typeof AdminOnlineRoute
  '/azeroth/status': typeof AzerothStatusRoute
  '/characters/$name': typeof CharactersNameRoute
  '/identity/users': typeof IdentityUsersRouteWithChildren
  '/items/$entry': typeof ItemsEntryRoute
  '/store/products': typeof StoreProductsRouteWithChildren
  '/store/wallet': typeof StoreWalletRoute
  '/account-links/': typeof AccountLinksIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/store/products/$sku': typeof StoreProductsSkuRoute
  '/identity/users/': typeof IdentityUsersIndexRoute
  '/store/products/': typeof StoreProductsIndexRoute
  '/identity/users/$userId/characters': typeof IdentityUsersUserIdCharactersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/login': typeof LoginRoute
  '/account-links/$userId': typeof AccountLinksUserIdRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/online': typeof AdminOnlineRoute
  '/azeroth/status': typeof AzerothStatusRoute
  '/characters/$name': typeof CharactersNameRoute
  '/items/$entry': typeof ItemsEntryRoute
  '/store/wallet': typeof StoreWalletRoute
  '/account-links': typeof AccountLinksIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/items': typeof ItemsIndexRoute
  '/store/products/$sku': typeof StoreProductsSkuRoute
  '/identity/users': typeof IdentityUsersIndexRoute
  '/store/products': typeof StoreProductsIndexRoute
  '/identity/users/$userId/characters': typeof IdentityUsersUserIdCharactersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-links': typeof AccountLinksRouteWithChildren
  '/accounts': typeof AccountsRoute
  '/login': typeof LoginRoute
  '/account-links/$userId': typeof AccountLinksUserIdRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/online': typeof AdminOnlineRoute
  '/azeroth/status': typeof AzerothStatusRoute
  '/characters/$name': typeof CharactersNameRoute
  '/identity/users': typeof IdentityUsersRouteWithChildren
  '/items/$entry': typeof ItemsEntryRoute
  '/store/products': typeof StoreProductsRouteWithChildren
  '/store/wallet': typeof StoreWalletRoute
  '/account-links/': typeof AccountLinksIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/store/products/$sku': typeof StoreProductsSkuRoute
  '/identity/users/': typeof IdentityUsersIndexRoute
  '/store/products/': typeof StoreProductsIndexRoute
  '/identity/users/$userId/characters': typeof IdentityUsersUserIdCharactersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-links'
    | '/accounts'
    | '/login'
    | '/account-links/$userId'
    | '/admin/accounts'
    | '/admin/online'
    | '/azeroth/status'
    | '/characters/$name'
    | '/identity/users'
    | '/items/$entry'
    | '/store/products'
    | '/store/wallet'
    | '/account-links/'
    | '/characters/'
    | '/items/'
    | '/store/products/$sku'
    | '/identity/users/'
    | '/store/products/'
    | '/identity/users/$userId/characters'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/login'
    | '/account-links/$userId'
    | '/admin/accounts'
    | '/admin/online'
    | '/azeroth/status'
    | '/characters/$name'
    | '/items/$entry'
    | '/store/wallet'
    | '/account-links'
    | '/characters'
    | '/items'
    | '/store/products/$sku'
    | '/identity/users'
    | '/store/products'
    | '/identity/users/$userId/characters'
  id:
    | '__root__'
    | '/'
    | '/account-links'
    | '/accounts'
    | '/login'
    | '/account-links/$userId'
    | '/admin/accounts'
    | '/admin/online'
    | '/azeroth/status'
    | '/characters/$name'
    | '/identity/users'
    | '/items/$entry'
    | '/store/products'
    | '/store/wallet'
    | '/account-links/'
    | '/characters/'
    | '/items/'
    | '/store/products/$sku'
    | '/identity/users/'
    | '/store/products/'
    | '/identity/users/$userId/characters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountLinksRoute: typeof AccountLinksRouteWithChildren
  AccountsRoute: typeof AccountsRoute
  LoginRoute: typeof LoginRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminOnlineRoute: typeof AdminOnlineRoute
  AzerothStatusRoute: typeof AzerothStatusRoute
  CharactersNameRoute: typeof CharactersNameRoute
  IdentityUsersRoute: typeof IdentityUsersRouteWithChildren
  ItemsEntryRoute: typeof ItemsEntryRoute
  StoreProductsRoute: typeof StoreProductsRouteWithChildren
  StoreWalletRoute: typeof StoreWalletRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-links': {
      id: '/account-links'
      path: '/account-links'
      fullPath: '/account-links'
      preLoaderRoute: typeof AccountLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-links/': {
      id: '/account-links/'
      path: '/'
      fullPath: '/account-links/'
      preLoaderRoute: typeof AccountLinksIndexRouteImport
      parentRoute: typeof AccountLinksRoute
    }
    '/account-links/$userId': {
      id: '/account-links/$userId'
      path: '/$userId'
      fullPath: '/account-links/$userId'
      preLoaderRoute: typeof AccountLinksUserIdRouteImport
      parentRoute: typeof AccountLinksRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/online': {
      id: '/admin/online'
      path: '/admin/online'
      fullPath: '/admin/online'
      preLoaderRoute: typeof AdminOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/azeroth/status': {
      id: '/azeroth/status'
      path: '/azeroth/status'
      fullPath: '/azeroth/status'
      preLoaderRoute: typeof AzerothStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$name': {
      id: '/characters/$name'
      path: '/characters/$name'
      fullPath: '/characters/$name'
      preLoaderRoute: typeof CharactersNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/users': {
      id: '/identity/users'
      path: '/identity/users'
      fullPath: '/identity/users'
      preLoaderRoute: typeof IdentityUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/': {
      id: '/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$entry': {
      id: '/items/$entry'
      path: '/items/$entry'
      fullPath: '/items/$entry'
      preLoaderRoute: typeof ItemsEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/products': {
      id: '/store/products'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof StoreProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/wallet': {
      id: '/store/wallet'
      path: '/store/wallet'
      fullPath: '/store/wallet'
      preLoaderRoute: typeof StoreWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/users/': {
      id: '/identity/users/'
      path: '/'
      fullPath: '/identity/users/'
      preLoaderRoute: typeof IdentityUsersIndexRouteImport
      parentRoute: typeof IdentityUsersRoute
    }
    '/store/products/': {
      id: '/store/products/'
      path: '/'
      fullPath: '/store/products/'
      preLoaderRoute: typeof StoreProductsIndexRouteImport
      parentRoute: typeof StoreProductsRoute
    }
    '/store/products/$sku': {
      id: '/store/products/$sku'
      path: '/$sku'
      fullPath: '/store/products/$sku'
      preLoaderRoute: typeof StoreProductsSkuRouteImport
      parentRoute: typeof StoreProductsRoute
    }
    '/identity/users/$userId/characters': {
      id: '/identity/users/$userId/characters'
      path: '/$userId/characters'
      fullPath: '/identity/users/$userId/characters'
      preLoaderRoute: typeof IdentityUsersUserIdCharactersRouteImport
      parentRoute: typeof IdentityUsersRoute
    }
  }
}

interface AccountLinksRouteChildren {
  AccountLinksUserIdRoute: typeof AccountLinksUserIdRoute
  AccountLinksIndexRoute: typeof AccountLinksIndexRoute
}

const AccountLinksRouteChildren: AccountLinksRouteChildren = {
  AccountLinksUserIdRoute: AccountLinksUserIdRoute,
  AccountLinksIndexRoute: AccountLinksIndexRoute,
}

const AccountLinksRouteWithChildren = AccountLinksRoute._addFileChildren(
  AccountLinksRouteChildren,
)

interface IdentityUsersRouteChildren {
  IdentityUsersIndexRoute: typeof IdentityUsersIndexRoute
  IdentityUsersUserIdCharactersRoute: typeof IdentityUsersUserIdCharactersRoute
}

const IdentityUsersRouteChildren: IdentityUsersRouteChildren = {
  IdentityUsersIndexRoute: IdentityUsersIndexRoute,
  IdentityUsersUserIdCharactersRoute: IdentityUsersUserIdCharactersRoute,
}

const IdentityUsersRouteWithChildren = IdentityUsersRoute._addFileChildren(
  IdentityUsersRouteChildren,
)

interface StoreProductsRouteChildren {
  StoreProductsSkuRoute: typeof StoreProductsSkuRoute
  StoreProductsIndexRoute: typeof StoreProductsIndexRoute
}

const StoreProductsRouteChildren: StoreProductsRouteChildren = {
  StoreProductsSkuRoute: StoreProductsSkuRoute,
  StoreProductsIndexRoute: StoreProductsIndexRoute,
}

const StoreProductsRouteWithChildren = StoreProductsRoute._addFileChildren(
  StoreProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountLinksRoute: AccountLinksRouteWithChildren,
  AccountsRoute: AccountsRoute,
  LoginRoute: LoginRoute,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminOnlineRoute: AdminOnlineRoute,
  AzerothStatusRoute: AzerothStatusRoute,
  CharactersNameRoute: CharactersNameRoute,
  IdentityUsersRoute: IdentityUsersRouteWithChildren,
  ItemsEntryRoute: ItemsEntryRoute,
  StoreProductsRoute: StoreProductsRouteWithChildren,
  StoreWalletRoute: StoreWalletRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
