/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PortalIndexRouteImport } from './routes/_portal/index'
import { Route as PortalForbiddenRouteImport } from './routes/_portal/forbidden'
import { Route as PortalLoginRouteImport } from './routes/_portal/login'
import { Route as PortalProfileRouteImport } from './routes/_portal/profile'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountsRouteImport } from './routes/admin/accounts'
import { Route as AdminOnlineRouteImport } from './routes/admin/online'
import { Route as PortalAzerothStatusRouteImport } from './routes/_portal/azeroth/status'
import { Route as PortalItemsIndexRouteImport } from './routes/_portal/items/index'
import { Route as PortalItemsEntryRouteImport } from './routes/_portal/items/$entry'
import { Route as PortalStoreProductsRouteImport } from './routes/_portal/store/products'
import { Route as PortalStoreWalletRouteImport } from './routes/_portal/store/wallet'
import { Route as AdminCharactersIndexRouteImport } from './routes/admin/characters/index'
import { Route as AdminCharactersNameRouteImport } from './routes/admin/characters/$name'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as PortalStoreProductsIndexRouteImport } from './routes/_portal/store/products.index'
import { Route as PortalStoreProductsSkuRouteImport } from './routes/_portal/store/products.$sku'

const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalForbiddenRoute = PortalForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnlineRoute = AdminOnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => AdminRoute,
} as any)
const PortalAzerothStatusRoute = PortalAzerothStatusRouteImport.update({
  id: '/azeroth/status',
  path: '/azeroth/status',
  getParentRoute: () => PortalRoute,
} as any)
const PortalItemsIndexRoute = PortalItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalItemsEntryRoute = PortalItemsEntryRouteImport.update({
  id: '/items/$entry',
  path: '/items/$entry',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStoreProductsRoute = PortalStoreProductsRouteImport.update({
  id: '/store/products',
  path: '/store/products',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStoreWalletRoute = PortalStoreWalletRouteImport.update({
  id: '/store/wallet',
  path: '/store/wallet',
  getParentRoute: () => PortalRoute,
} as any)
const AdminCharactersIndexRoute = AdminCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCharactersNameRoute = AdminCharactersNameRouteImport.update({
  id: '/characters/$name',
  path: '/characters/$name',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const PortalStoreProductsIndexRoute =
  PortalStoreProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PortalStoreProductsRoute,
  } as any)
const PortalStoreProductsSkuRoute = PortalStoreProductsSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => PortalStoreProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forbidden': typeof PortalForbiddenRoute
  '/login': typeof PortalLoginRoute
  '/profile': typeof PortalProfileRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/online': typeof AdminOnlineRoute
  '/admin/': typeof AdminIndexRoute
  '/azeroth/status': typeof PortalAzerothStatusRoute
  '/items/$entry': typeof PortalItemsEntryRoute
  '/store/products': typeof PortalStoreProductsRouteWithChildren
  '/store/wallet': typeof PortalStoreWalletRoute
  '/admin/characters/$name': typeof AdminCharactersNameRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/items/': typeof PortalItemsIndexRoute
  '/admin/characters/': typeof AdminCharactersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/store/products/$sku': typeof PortalStoreProductsSkuRoute
  '/store/products/': typeof PortalStoreProductsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof PortalForbiddenRoute
  '/login': typeof PortalLoginRoute
  '/profile': typeof PortalProfileRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/online': typeof AdminOnlineRoute
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminIndexRoute
  '/azeroth/status': typeof PortalAzerothStatusRoute
  '/items/$entry': typeof PortalItemsEntryRoute
  '/store/wallet': typeof PortalStoreWalletRoute
  '/admin/characters/$name': typeof AdminCharactersNameRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/items': typeof PortalItemsIndexRoute
  '/admin/characters': typeof AdminCharactersIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/store/products/$sku': typeof PortalStoreProductsSkuRoute
  '/store/products': typeof PortalStoreProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_portal/forbidden': typeof PortalForbiddenRoute
  '/_portal/login': typeof PortalLoginRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/online': typeof AdminOnlineRoute
  '/_portal/': typeof PortalIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_portal/azeroth/status': typeof PortalAzerothStatusRoute
  '/_portal/items/$entry': typeof PortalItemsEntryRoute
  '/_portal/store/products': typeof PortalStoreProductsRouteWithChildren
  '/_portal/store/wallet': typeof PortalStoreWalletRoute
  '/admin/characters/$name': typeof AdminCharactersNameRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_portal/items/': typeof PortalItemsIndexRoute
  '/admin/characters/': typeof AdminCharactersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_portal/store/products/$sku': typeof PortalStoreProductsSkuRoute
  '/_portal/store/products/': typeof PortalStoreProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/admin/accounts'
    | '/admin/online'
    | '/admin/'
    | '/azeroth/status'
    | '/items/$entry'
    | '/store/products'
    | '/store/wallet'
    | '/admin/characters/$name'
    | '/admin/users/$userId'
    | '/items/'
    | '/admin/characters/'
    | '/admin/users/'
    | '/store/products/$sku'
    | '/store/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/admin/accounts'
    | '/admin/online'
    | '/'
    | '/admin'
    | '/azeroth/status'
    | '/items/$entry'
    | '/store/wallet'
    | '/admin/characters/$name'
    | '/admin/users/$userId'
    | '/items'
    | '/admin/characters'
    | '/admin/users'
    | '/store/products/$sku'
    | '/store/products'
  id:
    | '__root__'
    | '/_portal'
    | '/admin'
    | '/_portal/forbidden'
    | '/_portal/login'
    | '/_portal/profile'
    | '/admin/accounts'
    | '/admin/online'
    | '/_portal/'
    | '/admin/'
    | '/_portal/azeroth/status'
    | '/_portal/items/$entry'
    | '/_portal/store/products'
    | '/_portal/store/wallet'
    | '/admin/characters/$name'
    | '/admin/users/$userId'
    | '/_portal/items/'
    | '/admin/characters/'
    | '/admin/users/'
    | '/_portal/store/products/$sku'
    | '/_portal/store/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/forbidden': {
      id: '/_portal/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof PortalForbiddenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/login': {
      id: '/_portal/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/online': {
      id: '/admin/online'
      path: '/online'
      fullPath: '/admin/online'
      preLoaderRoute: typeof AdminOnlineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/azeroth/status': {
      id: '/_portal/azeroth/status'
      path: '/azeroth/status'
      fullPath: '/azeroth/status'
      preLoaderRoute: typeof PortalAzerothStatusRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/items/': {
      id: '/_portal/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof PortalItemsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/items/$entry': {
      id: '/_portal/items/$entry'
      path: '/items/$entry'
      fullPath: '/items/$entry'
      preLoaderRoute: typeof PortalItemsEntryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/store/products': {
      id: '/_portal/store/products'
      path: '/store/products'
      fullPath: '/store/products'
      preLoaderRoute: typeof PortalStoreProductsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/store/wallet': {
      id: '/_portal/store/wallet'
      path: '/store/wallet'
      fullPath: '/store/wallet'
      preLoaderRoute: typeof PortalStoreWalletRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/characters/': {
      id: '/admin/characters/'
      path: '/characters'
      fullPath: '/admin/characters/'
      preLoaderRoute: typeof AdminCharactersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/characters/$name': {
      id: '/admin/characters/$name'
      path: '/characters/$name'
      fullPath: '/admin/characters/$name'
      preLoaderRoute: typeof AdminCharactersNameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/store/products/': {
      id: '/_portal/store/products/'
      path: '/'
      fullPath: '/store/products/'
      preLoaderRoute: typeof PortalStoreProductsIndexRouteImport
      parentRoute: typeof PortalStoreProductsRoute
    }
    '/_portal/store/products/$sku': {
      id: '/_portal/store/products/$sku'
      path: '/$sku'
      fullPath: '/store/products/$sku'
      preLoaderRoute: typeof PortalStoreProductsSkuRouteImport
      parentRoute: typeof PortalStoreProductsRoute
    }
  }
}

interface PortalStoreProductsRouteChildren {
  PortalStoreProductsSkuRoute: typeof PortalStoreProductsSkuRoute
  PortalStoreProductsIndexRoute: typeof PortalStoreProductsIndexRoute
}

const PortalStoreProductsRouteChildren: PortalStoreProductsRouteChildren = {
  PortalStoreProductsSkuRoute: PortalStoreProductsSkuRoute,
  PortalStoreProductsIndexRoute: PortalStoreProductsIndexRoute,
}

const PortalStoreProductsRouteWithChildren =
  PortalStoreProductsRoute._addFileChildren(PortalStoreProductsRouteChildren)

interface PortalRouteChildren {
  PortalForbiddenRoute: typeof PortalForbiddenRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAzerothStatusRoute: typeof PortalAzerothStatusRoute
  PortalItemsEntryRoute: typeof PortalItemsEntryRoute
  PortalStoreProductsRoute: typeof PortalStoreProductsRouteWithChildren
  PortalStoreWalletRoute: typeof PortalStoreWalletRoute
  PortalItemsIndexRoute: typeof PortalItemsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalForbiddenRoute: PortalForbiddenRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalAzerothStatusRoute: PortalAzerothStatusRoute,
  PortalItemsEntryRoute: PortalItemsEntryRoute,
  PortalStoreProductsRoute: PortalStoreProductsRouteWithChildren,
  PortalStoreWalletRoute: PortalStoreWalletRoute,
  PortalItemsIndexRoute: PortalItemsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminOnlineRoute: typeof AdminOnlineRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCharactersNameRoute: typeof AdminCharactersNameRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminCharactersIndexRoute: typeof AdminCharactersIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminOnlineRoute: AdminOnlineRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCharactersNameRoute: AdminCharactersNameRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminCharactersIndexRoute: AdminCharactersIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
