/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PortalIndexRouteImport } from './routes/_portal/index'
import { Route as PortalForbiddenRouteImport } from './routes/_portal/forbidden'
import { Route as PortalLoginRouteImport } from './routes/_portal/login'
import { Route as PortalProfileRouteImport } from './routes/_portal/profile'
import { Route as PortalReportRouteImport } from './routes/_portal/report'
import { Route as PortalWalletRouteImport } from './routes/_portal/wallet'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApiClientsRouteImport } from './routes/admin/api-clients'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminStoreRouteImport } from './routes/admin/store'
import { Route as PortalAzerothOnboardingRouteImport } from './routes/_portal/azeroth/onboarding'
import { Route as PortalAzerothStatusRouteImport } from './routes/_portal/azeroth/status'
import { Route as PortalStoreIndexRouteImport } from './routes/_portal/store/index'
import { Route as AdminAzerothOnlineRouteImport } from './routes/admin/azeroth/online'
import { Route as AdminStoreIndexRouteImport } from './routes/admin/store/index'
import { Route as AdminStoreSkuRouteImport } from './routes/admin/store/$sku'
import { Route as AdminStoreOrdersRouteImport } from './routes/admin/store/orders'
import { Route as AdminStoreWalletsRouteImport } from './routes/admin/store/wallets'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as PortalAzerothCharactersIndexRouteImport } from './routes/_portal/azeroth/characters/index'
import { Route as PortalAzerothLeaderboardsIndexRouteImport } from './routes/_portal/azeroth/leaderboards/index'
import { Route as PortalAzerothLeaderboardsBoardRouteImport } from './routes/_portal/azeroth/leaderboards/$board'
import { Route as PortalStoreProductsSkuRouteImport } from './routes/_portal/store/products.$sku'
import { Route as AdminAzerothAccountsIndexRouteImport } from './routes/admin/azeroth/accounts/index'
import { Route as AdminAzerothAccountsUsernameRouteImport } from './routes/admin/azeroth/accounts/$username'
import { Route as AdminAzerothCharactersIndexRouteImport } from './routes/admin/azeroth/characters/index'
import { Route as AdminAzerothCharactersNameRouteImport } from './routes/admin/azeroth/characters/$name'
import { Route as AdminAzerothItemsIndexRouteImport } from './routes/admin/azeroth/items/index'
import { Route as AdminAzerothItemsEntryRouteImport } from './routes/admin/azeroth/items/$entry'

const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalForbiddenRoute = PortalForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportRoute = PortalReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWalletRoute = PortalWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiClientsRoute = AdminApiClientsRouteImport.update({
  id: '/api-clients',
  path: '/api-clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoreRoute = AdminStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AdminRoute,
} as any)
const PortalAzerothOnboardingRoute = PortalAzerothOnboardingRouteImport.update({
  id: '/azeroth/onboarding',
  path: '/azeroth/onboarding',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAzerothStatusRoute = PortalAzerothStatusRouteImport.update({
  id: '/azeroth/status',
  path: '/azeroth/status',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStoreIndexRoute = PortalStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminAzerothOnlineRoute = AdminAzerothOnlineRouteImport.update({
  id: '/azeroth/online',
  path: '/azeroth/online',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoreIndexRoute = AdminStoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminStoreRoute,
} as any)
const AdminStoreSkuRoute = AdminStoreSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => AdminStoreRoute,
} as any)
const AdminStoreOrdersRoute = AdminStoreOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminStoreRoute,
} as any)
const AdminStoreWalletsRoute = AdminStoreWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminStoreRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const PortalAzerothCharactersIndexRoute =
  PortalAzerothCharactersIndexRouteImport.update({
    id: '/azeroth/characters/',
    path: '/azeroth/characters/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAzerothLeaderboardsIndexRoute =
  PortalAzerothLeaderboardsIndexRouteImport.update({
    id: '/azeroth/leaderboards/',
    path: '/azeroth/leaderboards/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAzerothLeaderboardsBoardRoute =
  PortalAzerothLeaderboardsBoardRouteImport.update({
    id: '/azeroth/leaderboards/$board',
    path: '/azeroth/leaderboards/$board',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalStoreProductsSkuRoute = PortalStoreProductsSkuRouteImport.update({
  id: '/store/products/$sku',
  path: '/store/products/$sku',
  getParentRoute: () => PortalRoute,
} as any)
const AdminAzerothAccountsIndexRoute =
  AdminAzerothAccountsIndexRouteImport.update({
    id: '/azeroth/accounts/',
    path: '/azeroth/accounts/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAzerothAccountsUsernameRoute =
  AdminAzerothAccountsUsernameRouteImport.update({
    id: '/azeroth/accounts/$username',
    path: '/azeroth/accounts/$username',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAzerothCharactersIndexRoute =
  AdminAzerothCharactersIndexRouteImport.update({
    id: '/azeroth/characters/',
    path: '/azeroth/characters/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAzerothCharactersNameRoute =
  AdminAzerothCharactersNameRouteImport.update({
    id: '/azeroth/characters/$name',
    path: '/azeroth/characters/$name',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAzerothItemsIndexRoute = AdminAzerothItemsIndexRouteImport.update({
  id: '/azeroth/items/',
  path: '/azeroth/items/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAzerothItemsEntryRoute = AdminAzerothItemsEntryRouteImport.update({
  id: '/azeroth/items/$entry',
  path: '/azeroth/items/$entry',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forbidden': typeof PortalForbiddenRoute
  '/login': typeof PortalLoginRoute
  '/profile': typeof PortalProfileRoute
  '/report': typeof PortalReportRoute
  '/wallet': typeof PortalWalletRoute
  '/admin/api-clients': typeof AdminApiClientsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/store': typeof AdminStoreRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/azeroth/onboarding': typeof PortalAzerothOnboardingRoute
  '/azeroth/status': typeof PortalAzerothStatusRoute
  '/admin/azeroth/online': typeof AdminAzerothOnlineRoute
  '/admin/store/$sku': typeof AdminStoreSkuRoute
  '/admin/store/orders': typeof AdminStoreOrdersRoute
  '/admin/store/wallets': typeof AdminStoreWalletsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/store/': typeof PortalStoreIndexRoute
  '/admin/store/': typeof AdminStoreIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/azeroth/leaderboards/$board': typeof PortalAzerothLeaderboardsBoardRoute
  '/store/products/$sku': typeof PortalStoreProductsSkuRoute
  '/admin/azeroth/accounts/$username': typeof AdminAzerothAccountsUsernameRoute
  '/admin/azeroth/characters/$name': typeof AdminAzerothCharactersNameRoute
  '/admin/azeroth/items/$entry': typeof AdminAzerothItemsEntryRoute
  '/azeroth/characters/': typeof PortalAzerothCharactersIndexRoute
  '/azeroth/leaderboards/': typeof PortalAzerothLeaderboardsIndexRoute
  '/admin/azeroth/accounts/': typeof AdminAzerothAccountsIndexRoute
  '/admin/azeroth/characters/': typeof AdminAzerothCharactersIndexRoute
  '/admin/azeroth/items/': typeof AdminAzerothItemsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof PortalForbiddenRoute
  '/login': typeof PortalLoginRoute
  '/profile': typeof PortalProfileRoute
  '/report': typeof PortalReportRoute
  '/wallet': typeof PortalWalletRoute
  '/admin/api-clients': typeof AdminApiClientsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminIndexRoute
  '/azeroth/onboarding': typeof PortalAzerothOnboardingRoute
  '/azeroth/status': typeof PortalAzerothStatusRoute
  '/admin/azeroth/online': typeof AdminAzerothOnlineRoute
  '/admin/store/$sku': typeof AdminStoreSkuRoute
  '/admin/store/orders': typeof AdminStoreOrdersRoute
  '/admin/store/wallets': typeof AdminStoreWalletsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/store': typeof PortalStoreIndexRoute
  '/admin/store': typeof AdminStoreIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/azeroth/leaderboards/$board': typeof PortalAzerothLeaderboardsBoardRoute
  '/store/products/$sku': typeof PortalStoreProductsSkuRoute
  '/admin/azeroth/accounts/$username': typeof AdminAzerothAccountsUsernameRoute
  '/admin/azeroth/characters/$name': typeof AdminAzerothCharactersNameRoute
  '/admin/azeroth/items/$entry': typeof AdminAzerothItemsEntryRoute
  '/azeroth/characters': typeof PortalAzerothCharactersIndexRoute
  '/azeroth/leaderboards': typeof PortalAzerothLeaderboardsIndexRoute
  '/admin/azeroth/accounts': typeof AdminAzerothAccountsIndexRoute
  '/admin/azeroth/characters': typeof AdminAzerothCharactersIndexRoute
  '/admin/azeroth/items': typeof AdminAzerothItemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_portal/forbidden': typeof PortalForbiddenRoute
  '/_portal/login': typeof PortalLoginRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/report': typeof PortalReportRoute
  '/_portal/wallet': typeof PortalWalletRoute
  '/admin/api-clients': typeof AdminApiClientsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/store': typeof AdminStoreRouteWithChildren
  '/_portal/': typeof PortalIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_portal/azeroth/onboarding': typeof PortalAzerothOnboardingRoute
  '/_portal/azeroth/status': typeof PortalAzerothStatusRoute
  '/admin/azeroth/online': typeof AdminAzerothOnlineRoute
  '/admin/store/$sku': typeof AdminStoreSkuRoute
  '/admin/store/orders': typeof AdminStoreOrdersRoute
  '/admin/store/wallets': typeof AdminStoreWalletsRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_portal/store/': typeof PortalStoreIndexRoute
  '/admin/store/': typeof AdminStoreIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_portal/azeroth/leaderboards/$board': typeof PortalAzerothLeaderboardsBoardRoute
  '/_portal/store/products/$sku': typeof PortalStoreProductsSkuRoute
  '/admin/azeroth/accounts/$username': typeof AdminAzerothAccountsUsernameRoute
  '/admin/azeroth/characters/$name': typeof AdminAzerothCharactersNameRoute
  '/admin/azeroth/items/$entry': typeof AdminAzerothItemsEntryRoute
  '/_portal/azeroth/characters/': typeof PortalAzerothCharactersIndexRoute
  '/_portal/azeroth/leaderboards/': typeof PortalAzerothLeaderboardsIndexRoute
  '/admin/azeroth/accounts/': typeof AdminAzerothAccountsIndexRoute
  '/admin/azeroth/characters/': typeof AdminAzerothCharactersIndexRoute
  '/admin/azeroth/items/': typeof AdminAzerothItemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/report'
    | '/wallet'
    | '/admin/api-clients'
    | '/admin/audit'
    | '/admin/moderation'
    | '/admin/roles'
    | '/admin/store'
    | '/admin/'
    | '/azeroth/onboarding'
    | '/azeroth/status'
    | '/admin/azeroth/online'
    | '/admin/store/$sku'
    | '/admin/store/orders'
    | '/admin/store/wallets'
    | '/admin/users/$userId'
    | '/store/'
    | '/admin/store/'
    | '/admin/users/'
    | '/azeroth/leaderboards/$board'
    | '/store/products/$sku'
    | '/admin/azeroth/accounts/$username'
    | '/admin/azeroth/characters/$name'
    | '/admin/azeroth/items/$entry'
    | '/azeroth/characters/'
    | '/azeroth/leaderboards/'
    | '/admin/azeroth/accounts/'
    | '/admin/azeroth/characters/'
    | '/admin/azeroth/items/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/profile'
    | '/report'
    | '/wallet'
    | '/admin/api-clients'
    | '/admin/audit'
    | '/admin/moderation'
    | '/admin/roles'
    | '/'
    | '/admin'
    | '/azeroth/onboarding'
    | '/azeroth/status'
    | '/admin/azeroth/online'
    | '/admin/store/$sku'
    | '/admin/store/orders'
    | '/admin/store/wallets'
    | '/admin/users/$userId'
    | '/store'
    | '/admin/store'
    | '/admin/users'
    | '/azeroth/leaderboards/$board'
    | '/store/products/$sku'
    | '/admin/azeroth/accounts/$username'
    | '/admin/azeroth/characters/$name'
    | '/admin/azeroth/items/$entry'
    | '/azeroth/characters'
    | '/azeroth/leaderboards'
    | '/admin/azeroth/accounts'
    | '/admin/azeroth/characters'
    | '/admin/azeroth/items'
  id:
    | '__root__'
    | '/_portal'
    | '/admin'
    | '/_portal/forbidden'
    | '/_portal/login'
    | '/_portal/profile'
    | '/_portal/report'
    | '/_portal/wallet'
    | '/admin/api-clients'
    | '/admin/audit'
    | '/admin/moderation'
    | '/admin/roles'
    | '/admin/store'
    | '/_portal/'
    | '/admin/'
    | '/_portal/azeroth/onboarding'
    | '/_portal/azeroth/status'
    | '/admin/azeroth/online'
    | '/admin/store/$sku'
    | '/admin/store/orders'
    | '/admin/store/wallets'
    | '/admin/users/$userId'
    | '/_portal/store/'
    | '/admin/store/'
    | '/admin/users/'
    | '/_portal/azeroth/leaderboards/$board'
    | '/_portal/store/products/$sku'
    | '/admin/azeroth/accounts/$username'
    | '/admin/azeroth/characters/$name'
    | '/admin/azeroth/items/$entry'
    | '/_portal/azeroth/characters/'
    | '/_portal/azeroth/leaderboards/'
    | '/admin/azeroth/accounts/'
    | '/admin/azeroth/characters/'
    | '/admin/azeroth/items/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/forbidden': {
      id: '/_portal/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof PortalForbiddenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/login': {
      id: '/_portal/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/report': {
      id: '/_portal/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof PortalReportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/wallet': {
      id: '/_portal/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof PortalWalletRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-clients': {
      id: '/admin/api-clients'
      path: '/api-clients'
      fullPath: '/admin/api-clients'
      preLoaderRoute: typeof AdminApiClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/store': {
      id: '/admin/store'
      path: '/store'
      fullPath: '/admin/store'
      preLoaderRoute: typeof AdminStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/azeroth/onboarding': {
      id: '/_portal/azeroth/onboarding'
      path: '/azeroth/onboarding'
      fullPath: '/azeroth/onboarding'
      preLoaderRoute: typeof PortalAzerothOnboardingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/azeroth/status': {
      id: '/_portal/azeroth/status'
      path: '/azeroth/status'
      fullPath: '/azeroth/status'
      preLoaderRoute: typeof PortalAzerothStatusRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/store/': {
      id: '/_portal/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof PortalStoreIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/azeroth/online': {
      id: '/admin/azeroth/online'
      path: '/azeroth/online'
      fullPath: '/admin/azeroth/online'
      preLoaderRoute: typeof AdminAzerothOnlineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/store/': {
      id: '/admin/store/'
      path: '/'
      fullPath: '/admin/store/'
      preLoaderRoute: typeof AdminStoreIndexRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/admin/store/$sku': {
      id: '/admin/store/$sku'
      path: '/$sku'
      fullPath: '/admin/store/$sku'
      preLoaderRoute: typeof AdminStoreSkuRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/admin/store/orders': {
      id: '/admin/store/orders'
      path: '/orders'
      fullPath: '/admin/store/orders'
      preLoaderRoute: typeof AdminStoreOrdersRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/admin/store/wallets': {
      id: '/admin/store/wallets'
      path: '/wallets'
      fullPath: '/admin/store/wallets'
      preLoaderRoute: typeof AdminStoreWalletsRouteImport
      parentRoute: typeof AdminStoreRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_portal/azeroth/characters/': {
      id: '/_portal/azeroth/characters/'
      path: '/azeroth/characters'
      fullPath: '/azeroth/characters/'
      preLoaderRoute: typeof PortalAzerothCharactersIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/azeroth/leaderboards/': {
      id: '/_portal/azeroth/leaderboards/'
      path: '/azeroth/leaderboards'
      fullPath: '/azeroth/leaderboards/'
      preLoaderRoute: typeof PortalAzerothLeaderboardsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/azeroth/leaderboards/$board': {
      id: '/_portal/azeroth/leaderboards/$board'
      path: '/azeroth/leaderboards/$board'
      fullPath: '/azeroth/leaderboards/$board'
      preLoaderRoute: typeof PortalAzerothLeaderboardsBoardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/store/products/$sku': {
      id: '/_portal/store/products/$sku'
      path: '/store/products/$sku'
      fullPath: '/store/products/$sku'
      preLoaderRoute: typeof PortalStoreProductsSkuRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/azeroth/accounts/': {
      id: '/admin/azeroth/accounts/'
      path: '/azeroth/accounts'
      fullPath: '/admin/azeroth/accounts/'
      preLoaderRoute: typeof AdminAzerothAccountsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/azeroth/accounts/$username': {
      id: '/admin/azeroth/accounts/$username'
      path: '/azeroth/accounts/$username'
      fullPath: '/admin/azeroth/accounts/$username'
      preLoaderRoute: typeof AdminAzerothAccountsUsernameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/azeroth/characters/': {
      id: '/admin/azeroth/characters/'
      path: '/azeroth/characters'
      fullPath: '/admin/azeroth/characters/'
      preLoaderRoute: typeof AdminAzerothCharactersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/azeroth/characters/$name': {
      id: '/admin/azeroth/characters/$name'
      path: '/azeroth/characters/$name'
      fullPath: '/admin/azeroth/characters/$name'
      preLoaderRoute: typeof AdminAzerothCharactersNameRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/azeroth/items/': {
      id: '/admin/azeroth/items/'
      path: '/azeroth/items'
      fullPath: '/admin/azeroth/items/'
      preLoaderRoute: typeof AdminAzerothItemsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/azeroth/items/$entry': {
      id: '/admin/azeroth/items/$entry'
      path: '/azeroth/items/$entry'
      fullPath: '/admin/azeroth/items/$entry'
      preLoaderRoute: typeof AdminAzerothItemsEntryRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PortalRouteChildren {
  PortalForbiddenRoute: typeof PortalForbiddenRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalReportRoute: typeof PortalReportRoute
  PortalWalletRoute: typeof PortalWalletRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAzerothOnboardingRoute: typeof PortalAzerothOnboardingRoute
  PortalAzerothStatusRoute: typeof PortalAzerothStatusRoute
  PortalStoreIndexRoute: typeof PortalStoreIndexRoute
  PortalAzerothLeaderboardsBoardRoute: typeof PortalAzerothLeaderboardsBoardRoute
  PortalStoreProductsSkuRoute: typeof PortalStoreProductsSkuRoute
  PortalAzerothCharactersIndexRoute: typeof PortalAzerothCharactersIndexRoute
  PortalAzerothLeaderboardsIndexRoute: typeof PortalAzerothLeaderboardsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalForbiddenRoute: PortalForbiddenRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalReportRoute: PortalReportRoute,
  PortalWalletRoute: PortalWalletRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalAzerothOnboardingRoute: PortalAzerothOnboardingRoute,
  PortalAzerothStatusRoute: PortalAzerothStatusRoute,
  PortalStoreIndexRoute: PortalStoreIndexRoute,
  PortalAzerothLeaderboardsBoardRoute: PortalAzerothLeaderboardsBoardRoute,
  PortalStoreProductsSkuRoute: PortalStoreProductsSkuRoute,
  PortalAzerothCharactersIndexRoute: PortalAzerothCharactersIndexRoute,
  PortalAzerothLeaderboardsIndexRoute: PortalAzerothLeaderboardsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface AdminStoreRouteChildren {
  AdminStoreSkuRoute: typeof AdminStoreSkuRoute
  AdminStoreOrdersRoute: typeof AdminStoreOrdersRoute
  AdminStoreWalletsRoute: typeof AdminStoreWalletsRoute
  AdminStoreIndexRoute: typeof AdminStoreIndexRoute
}

const AdminStoreRouteChildren: AdminStoreRouteChildren = {
  AdminStoreSkuRoute: AdminStoreSkuRoute,
  AdminStoreOrdersRoute: AdminStoreOrdersRoute,
  AdminStoreWalletsRoute: AdminStoreWalletsRoute,
  AdminStoreIndexRoute: AdminStoreIndexRoute,
}

const AdminStoreRouteWithChildren = AdminStoreRoute._addFileChildren(
  AdminStoreRouteChildren,
)

interface AdminRouteChildren {
  AdminApiClientsRoute: typeof AdminApiClientsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminStoreRoute: typeof AdminStoreRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAzerothOnlineRoute: typeof AdminAzerothOnlineRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminAzerothAccountsUsernameRoute: typeof AdminAzerothAccountsUsernameRoute
  AdminAzerothCharactersNameRoute: typeof AdminAzerothCharactersNameRoute
  AdminAzerothItemsEntryRoute: typeof AdminAzerothItemsEntryRoute
  AdminAzerothAccountsIndexRoute: typeof AdminAzerothAccountsIndexRoute
  AdminAzerothCharactersIndexRoute: typeof AdminAzerothCharactersIndexRoute
  AdminAzerothItemsIndexRoute: typeof AdminAzerothItemsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiClientsRoute: AdminApiClientsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminStoreRoute: AdminStoreRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAzerothOnlineRoute: AdminAzerothOnlineRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminAzerothAccountsUsernameRoute: AdminAzerothAccountsUsernameRoute,
  AdminAzerothCharactersNameRoute: AdminAzerothCharactersNameRoute,
  AdminAzerothItemsEntryRoute: AdminAzerothItemsEntryRoute,
  AdminAzerothAccountsIndexRoute: AdminAzerothAccountsIndexRoute,
  AdminAzerothCharactersIndexRoute: AdminAzerothCharactersIndexRoute,
  AdminAzerothItemsIndexRoute: AdminAzerothItemsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
